//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramConstruction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person(string Name, string Telefon, string Mail, string Work, int Nr)
        {
            this.Name = Name;
            this.Telefon = Telefon;
            this.Mail = Mail;
            this.Work = Work;
            this.Nr = Nr;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Work { get; set; }
        public Nullable<int> Nr { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
